### ISSUE TITLE
Website hasn't been updated since 2017

### ISSUE THREAD

**Issue by dleslie** [CSSS/csss.cs.sfu.ca#6]
It looks as though the society is dead, which isn't a good look should the society go courting for funds from sponsors.

**Comment by modernNeo** [comment]
Hi @dleslie , the society is not dead, it is fully active. the website is up to date as you can see from our list of officers [http://sfucsss.org/about/officers/] as well as our commit history. the reason the main page is not up to date is cause of a slow migration to a new website which is taking time as I have other responsibilities I need to tend to while working on the new site.

**Comment by dleslie** [comment]
And yet, the most recent activity on **the front page** of the website is from 2017.

**Comment by dleslie** [comment]
![image](https://user-images.githubusercontent.com/107413/55031249-6ef4c080-4fcb-11e9-9832-d96fd8298000.png)

**Comment by dleslie** [comment]
If the migration is _in progress_ then this bug isn't finished.
